# Generated by Django 3.1.4 on 2021-01-05 02:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(default=accounts.models.create_password, max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_active_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
