# Generated by Django 3.1.4 on 2021-01-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_password',
            new_name='password',
        ),
    ]
