# Generated by Django 3.1.5 on 2021-01-30 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['creation_date']},
        ),
    ]
